=== MOSEK/sdocml/dtd/sdocmldefs.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- Include global entity definitions -->
<!ENTITY % HTMLsymbol  SYSTEM "external/HTMLsymbol.ent">  <!-- Original source: "http://www.w3.org/TR/html4/HTMLsymbol.ent"  -->
<!ENTITY % HTMLspecial SYSTEM "external/HTMLspecial.ent"> <!-- Original source: "http://www.w3.org/TR/html4/HTMLspecial.ent" -->
<!ENTITY % HTMLlat1    SYSTEM "external/HTMLlat1.ent">    <!-- Original source: "http://www.w3.org/TR/html4/HTMLlat1.ent"    -->
%HTMLsymbol;
%HTMLspecial;
%HTMLlat1;

<!ELEMENT defines ((def|incdef|defenv)*)>

<!ELEMENT defenv (desc?,defines?,(e|c|d)*)>
<!ATTLIST defenv 
                m CDATA #REQUIRED
                n CDATA "0">
    

<!ELEMENT def (desc?,(e|c|d)*)>
<!ATTLIST def m     CDATA #REQUIRED
              n     CDATA "0">
    <!ELEMENT d (#PCDATA)>
    <!ELEMENT c (arg*)>
    <!ATTLIST c n CDATA #REQUIRED>
        <!ELEMENT arg ((e|c|d)*)>
    <!ELEMENT e ((attr)*,(e|c|d)*)>
    <!ATTLIST e n CDATA #REQUIRED>
    <!ELEMENT attr EMPTY>
    <!ATTLIST attr n NMTOKEN #REQUIRED
                   v CDATA   #REQUIRED>

<!ELEMENT incdef EMPTY>
<!ATTLIST incdef url CDATA #REQUIRED
                 type CDATA #FIXED "text/mtkdef">

=== MOSEK/sdocml/manual/include/math.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE defines SYSTEM "http://sdocsml.googlecode.com/dtd/1.0a/sdocmldefs.dtd">

<defines>
  <!-- Math fonts -->
  <def m="mathcal"  n="1"><e n="mfont"><attr n="family">mathcal</attr><d>{{0}}</d></e></def>
  <def m="mathfrac" n="1"><e n="mfont"><attr n="family">mathfrac</attr><d>{{0}}</d></e></def>
  <def m="mathbb"   n="1"><e n="mfont"><attr n="family">mathbb</attr><d>{{0}}</d></e></def>
  <def m="mathbf"   n="1"><e n="mfont"><attr n="family">mathbf</attr><d>{{0}}</d></e></def> <!-- Not correct - should be style="mathbf" -->
  <def m="mathtt"   n="1"><e n="mfont"><attr n="family">mathtt</attr><d>{{0}}</d></e></def>
  <def m="mathit"   n="1"><e n="mfont"><attr n="family">mathit</attr><d>{{0}}</d></e></def>
  <def m="mbox"     n="1"><e n="mtext"><d>{{0}}</d></e></def>

  <def m="hat" n="1">
    <desc>This operator accepts exactly one char of the ones listed in accents.xml</desc>
    <e n="mo"><d><lookup>accentable-{{0}}</lookup>{{0}}&#x0302;</d></e>
  </def>
  <def m="bar" n="1">
    <e n="mo"><d><lookup>accentable-{{0}}</lookup>{{0}}&#x0304;</d></e>
  </def>
  <def m="underbar" n="1">
    <e n="mo"><d><lookup>accentable-{{0}}</lookup>{{0}}&#x0332;</d></e> <!--0x332 : Combining Low Line -->
  </def>

  <!-- Math macros-->
  <def m="frac" n="2"> <e n="mfrac"> <e n="mrow"> <d>{{0}}</d> </e> <e n="mrow"> <d>{{1}}</d> </e></e> </def>
  <def m="sqrt" n="1"> <e n="msqrt"> <e n="mrow"> <d>{{0}}</d> </e> </e></def>
  
  <def m="Cup" superscript-arg="yes" subscript-arg="yes">
    <desc>Indexed union; works like sum and prod.</desc> 
    <e n="msubsup">
      <e n="mrow"><e n="mo"><attr n="op">cup</attr></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
      <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
    </e>
  </def>
  <def m="Cap" superscript-arg="yes" subscript-arg="yes">
    <desc>Indexed intersection; works like sum and prod.</desc> 
    <e n="msubsup">
      <e n="mrow"><e n="mo"><attr n="op">cap</attr></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
      <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
    </e>
  </def>
  <def m="sum" superscript-arg="yes" subscript-arg="yes">
    <e n="msubsup">
      <e n="mrow"><e n="mo"><attr n="op">sum</attr></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
      <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
    </e>
  </def>
  
  <def m="prod" superscript-arg="yes" subscript-arg="yes">
    <e n="msubsup">
      <e n="mrow"><e n="mo"><attr n="op">prod</attr></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
      <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
    </e>
  </def>
    
  <def m="int" superscript-arg="yes" subscript-arg="yes">
    <e n="msubsup">
      <e n="mrow"><e n="mo"><attr n="op">int</attr></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
      <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
    </e>
  </def>

  <def m="vert" n="1"><e n="mfenced"><attr n="open">|</attr><attr n="close">|</attr><d>{{0}}</d></e></def>
  <def m="paren" n="1"><e n="mfenced"><attr n="open">(</attr><attr n="close">)</attr><d>{{0}}</d></e></def>
  <def m="limits"> <e n="mo"><attr n="op">limits</attr></e></def>
  <!-- <def m="notin">  <e n="mo"><d>&notin;</d></e></def> --> <!-- REPLACED BY \not{\in} -->
  <def m="norm" n="1"><e n="mfenced"><attr n="open">||</attr><attr n="close">||</attr><d>{{0}}</d></e></def>
  <def m="abs" n="1"><e n="mfenced"><attr n="open">|</attr><attr n="close">|</attr><d>{{0}}</d></e></def>
        
  <defenv m="braces"><e n="mfenced"><attr n="open">{</attr><attr n="close">}</attr><d>{{BODY}}</d></e></defenv>
  <defenv m="brackets"><e n="mfenced"><attr n="open">[</attr><attr n="close">]</attr><d>{{BODY}}</d></e></defenv>
  <defenv m="parens"><e n="mfenced"><attr n="open">(</attr><attr n="close">)</attr><d>{{BODY}}</d></e></defenv>
  <defenv m="leftbrace"><e n="mfenced"><attr n="open">{</attr><attr n="close"></attr><d>{{BODY}}</d></e></defenv>

  <def m="min" subscript-arg="yes">
    <e n="msub">
      <e n="mrow"><e n="mtext"><d>min</d></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
    </e>     
  </def>
  <def m="max" subscript-arg="yes">
    <e n="msub">
      <e n="mrow"><e n="mtext"><d>max</d></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
    </e>     
  </def>
  <def m="sup" subscript-arg="yes">
    <e n="msub">
      <e n="mrow"><e n="mtext"><d>sup</d></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
    </e>     
  </def>
  <def m="inf" subscript-arg="yes">
    <e n="msub">
      <e n="mrow"><e n="mtext"><d>inf</d></e></e>
      <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
    </e>     
  </def>






  <defenv m="math">
    <desc>Unnumbered math environment.</desc>
    <defines>
      <def m="tt" n="1"><e n="mfont"><attr n="family">mathtt</attr><d>{{0}}</d></e></def>
      <def m="rm" n="1"><e n="mfont"><attr n="family">mathrm</attr><d>{{0}}</d></e></def>
    </defines>
    <e n="math"><d>{{BODY}}</d></e>
  </defenv>
  
  <defenv m="equation" n="1">
    <desc>Numbered math environment.</desc>
    <defines>
      <def m="tt" n="1"><e n="mfont"><attr n="family">mathtt</attr><d>{{0}}</d></e></def>
      <def m="rm" n="1"><e n="mfont"><attr n="family">mathrm</attr><d>{{0}}</d></e></def>
    </defines>
    <e n="math"><attr n="id">{{0}}</attr> <d>{{BODY}}</d></e>
  </defenv>

  <def m="m" n="1">
    <desc>Inline math.</desc>
    <e n="m"><d>{{0}}</d></e>
  </def>


  <!-- Some standard function names -->

  <def m="diag">
    <desc>Diagonal of a square matrix.</desc>
    <e n="mtext"><d>diag</d></e>
  </def>
  
  <def m="Diag">
    <desc>Diagonal matrix from a vector.</desc>
    <e n="mtext"><d>Diag</d></e>
  </def>
  
  <def m="sin">
    <desc>Sinus.</desc>
    <e n="mtext"><d>sin</d></e>
  </def>

  <def m="cos">
    <desc>Sinus.</desc>
    <e n="mtext"><d>cos</d></e>
  </def>
  
</defines>

=== MOSEK/sdocml/manual/include/defs.xml
<?xml version="1.0" ?>
<!DOCTYPE defines SYSTEM "sdocmldefs.dtd">
<defines>
  <def m="tagref" n="1"><e n="ref"><attr n="ref">section:tagref:element:{{0}}</attr><e n="tt"><d>&lt;{{0}}&gt;</d></e></e></def>
  <def m="tag" n="1"><e n="tt"><d>&lt;{{0}}&gt;</d></e></def>
  <def m="endtag" n="1"><e n="tt"><d>&lt;/{{0}}&gt;</d></e></def>

  <!--
  <def m="tagitem" n="2">
    <e n="dt"><e n="ref"><attr n="ref">section:tagref:element:{{0}}</attr><e n="tt"><d>&lt;{{0}}&gt;</d></e></e></e>
    <e n="dd"><d>{{1}}</d></e>
  </def>
  -->
  <defenv m="tagdeflist">
    <defines>
      <def m="item" n="2">
        <e n="dt">
          <e n="ref">
            <attr n="ref">section:tagref:element:{{0}}</attr>
            <e n="tt"><d>&lt;{{0}}&gt;</d></e>
          </e>
        </e>
        <e n="dd"><d>{{1}}</d></e>
      </def>
    </defines>
    <e n="dlist"><attr n="class">tag-list</attr><d>{{BODY}}</d></e></defenv>
</defines>

=== MOSEK/sdocml/manual/include/base.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE defines SYSTEM "http://sdocsml.googlecode.com/dtd/1.0a/sdocmldefs.dtd">

<defines>
    <def m="sdocml"><e n="tt"><d>SDocML</d></e></def>
    
    <incdef url="accent.xml"/>
    <incdef url="syms.xml"/>
    <!-- Accent tables: Hat, bar and not --> 

    <!-- NOTE: Accents can be produced using combining characters, but the HTML backend does not support this yet. 
         The accenting macros use combining characters; the dictionary lookup expands to nothing but will only succeed if 
         the character was listed in then "accentable" list (accent.xml).
         Combining characters are defined in Unicode 0x0300-0x036f.
      -->
    <def m="hat" n="1">
      <desc>This operator accepts exactly one char of the ones listed in accents.xml</desc>
      <e n="mo"><d><lookup>accentable-{{0}}</lookup>{{0}}&#x0302;</d></e>
    </def>
    <def m="bar" n="1"><e n="mo"><d><lookup>accentable-{{0}}</lookup>{{0}}&#x0304;</d></e></def>

    <!-- An anchor generated with \index or \dindex contains no ID, and thus cannot be referred. -->

    <def m="index"  n="1">
      <desc>
        Define an index entry. The standard TeX syntax is allowed, but it is
        not processed by the frontend --- it will be up to the backend to
        interpret it. The expected TeX syntax is: a "!" separated list of keys,
        where each key is either a string "XYZ" defining the sort-key and the index entry, or a
        "XYZ@QWE" where "XYZ" is the sort-key and "QWE" is the index entry. The
        sort-key should never contain XML elements.
      </desc>
      <e n="a"><attr n="class">index</attr><d>{{0}}</d></e>
    </def>
    <def m="label"  n="1">
      <desc>Create a link target without a default link text as a point in the text.</desc>
      <e n="a">
        <attr n="class">label</attr>
        <attr n="id">{{0}}</attr>
      </e>
    </def>
    <def m="xlabel" n="2">
      <desc>Create a link target and use the second argument as default link text.</desc>
      <e n="a">
        <attr n="class">label</attr>
        <attr n="id">{{0}}</attr>
        <d>{{1}}</d>
      </e>
    </def>

    <def m="ref"   n="1">
      <desc>Generic reference to an ID within the expanded document. The target node is expected to provide link text. </desc>
      <e n="ref"> <attr n="ref">{{0}}</attr></e>
    </def>
    <def m="fref"  n="1">
      <desc>The same as a "ref", but it put paranthesis around the text. </desc>
      <d>(</d><e n="ref"> <attr n="ref">{{0}}</attr><attr n="class">fref</attr></e><d>)</d>
    </def> 
    <def m="reft"  n="2">
      <desc>The same as a "ref", but the second argument is used as link text.</desc>
      <e n="ref"> <attr n="ref">{{0}}</attr><d>{{1}}</d></e>
    </def>
    <def m="href"  n="1">
      <desc>Define a hyperlink to an external resource and use the link itself as link text. </desc>
      <e n="href"><attr n="url">{{0}}</attr></e>
    </def>
    <def m="url"  n="1"> 
      <desc>Alias for \href. </desc>
      <e n="href"><attr n="url">{{0}}</attr><d>{{0}}</d></e>
    </def>
     <def m="hreft" n="2">
      <desc>Define a hyperlink to an external resource and use the second argument as link text. </desc>
      <e n="href"><attr n="url">{{0}}</attr><d>{{1}}</d></e>
    </def>

    <def m="cite"  n="1">
      <desc>Define a bibliography link to an unresolved source. The external resource identifier is fixed to "bibdb", and the class is "cite". </desc>
      <e n="ref"><attr n="class">cite</attr><attr n="type">cite</attr><attr n="ref">{{0}}</attr></e>
    </def>

    <def m="tt"   n="1"><e n="tt"><d>{{0}}</d></e></def> <!-- Typed text-->
    <def m="it"   n="1"><e n="it"><d>{{0}}</d></e></def> <!-- Italic -->
    <def m="em"   n="1"><e n="em"><d>{{0}}</d></e></def> <!-- Emphasized -->
    <def m="emph" n="1"><e n="em"><d>{{0}}</d></e></def> <!-- Emphasized -->
    <def m="bf"   n="1"><e n="bf"><d>{{0}}</d></e></def> <!-- Bold face -->
    <def m="sc"   n="1"><e n="sc"><d>{{0}}</d></e></def> <!-- Small Caps -->

    <def m="texttt" n="1"><e n="tt"><d>{{0}}</d></e></def>
    <def m="br"><e n="br"/></def>


    <!-- Math fonts -->
    <def m="mathcal"  n="1"><e n="mfont"><attr n="family">mathcal</attr><d>{{0}}</d></e></def>
    <def m="mathfrac" n="1"><e n="mfont"><attr n="family">mathfrac</attr><d>{{0}}</d></e></def>
    <def m="mathbb"   n="1"><e n="mfont"><attr n="family">mathbb</attr><d>{{0}}</d></e></def>
    <def m="mathtt"   n="1"><e n="mfont"><attr n="family">mathtt</attr><d>{{0}}</d></e></def>
    <def m="mbox"     n="1"><e n="mtext"><d>{{0}}</d></e></def>

    <!-- Math macros-->
    <def m="frac" n="2"> <e n="mfrac"> <e n="mrow"> <d>{{0}}</d> </e> <e n="mrow"> <d>{{1}}</d> </e></e> </def>
    <def m="sqrt" n="1"> <e n="msqrt"> <e n="mrow"> <d>{{0}}</d> </e> </e></def>

    <def m="sum" superscript-arg="yes" subscript-arg="yes">
      <e n="msubsup">
        <e n="mrow"><e n="mo"><attr n="op">sum</attr></e></e>
        <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
        <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
      </e>
    </def>
    
    <def m="int" superscript-arg="yes" subscript-arg="yes">
      <e n="msubsup">
        <e n="mrow"><e n="mo"><attr n="op">int</attr></e></e>
        <e n="mrow"><d>{{SUBSCRIPT}}</d></e>
        <e n="mrow"><d>{{SUPERSCRIPT}}</d></e>
      </e>
    </def>

    <def m="limits"> <e n="mo"><attr n="op">limits</attr></e></def>
    <!-- <def m="notin">  <e n="mo"><d>&notin;</d></e></def> --> <!-- REPLACED BY \not{\in} -->
    <def m="norm" n="1"><e n="mfenced"><attr n="open">&Vert;</attr><attr n="close">&Vert;</attr><d>{{0}}</d></e></def>
          
    <defenv m="braces"><e n="mfenced"><attr n="open">{</attr><attr n="close">}</attr><d>{{BODY}}</d></e></defenv>
    <defenv m="backets"><e n="mfenced"><attr n="open">[</attr><attr n="close">]</attr><d>{{BODY}}</d></e></defenv>
    <defenv m="parens"><e n="mfenced"><attr n="open">(</attr><attr n="close">)</attr><d>{{BODY}}</d></e></defenv>
    <defenv m="leftbrace"><e n="mfenced"><attr n="open">{</attr><attr n="close"></attr><d>{{BODY}}</d></e></defenv>
  
   

    <!-- Some simple environments -->
    <defenv m="itemize">
      <desc>Itemize list. Use the \item{text} macro to add list items. </desc>
      <e n="ilist">
        <attr n="class">itemize</attr>
        <d>{{BODY}}</d>
      </e>
    </defenv>
    <def m="item" n="1"><e n="li"><d>{{0}}</d></e></def>
    
    <defenv m="enumerate">
      <desc>Enumerated list. Use the \item{text} macro to add list items. </desc>
      <e n="ilist"><attr n="class">enumerate</attr><d>{{BODY}}</d></e>
    </defenv>
    
    <defenv m="description">
      <desc>Definition list. Use the \ditem{label}{text} macro to add list items. </desc>
      <e n="dlist"><d>{{BODY}}</d></e>
    </defenv>
    <def m="ditem" n="2">
      <e n="dt"><d>{{0}}</d></e>
      <e n="dd"><d>{{1}}</d></e>
    </def>

    <defenv m="figure">
      <e n="float">
        <attr n="class">figure</attr>
        <d>{{BODY}}</d>
      </e>
    </defenv>
</defines>

=== MOSEK/sdocml/manual/include/syms.xml
<?xml version="0.0" encoding="utf-8"?>
<!DOCTYPE defines SYSTEM "http://sdocsml.googlecode.com/dtd/1.0a/sdocmldefs.dtd">

<defines>
    <!-- Symbol definitions -->

    <def m="peace"><d>&#x262e;</d></def> 

    <def m="\"><d>\</d></def> <!-- escaped backslash -->
    <def m=" "><d>&nbsp;</d></def> <!-- escaped backslash -->
    <def m="_"><d>_</d></def> <!-- escaped underscore -->
    <def m="^"><d>^</d></def> <!-- escaped circumflex -->
    <def m="{"><d>{</d></def> 
    <def m="}"><d>}</d></def> 
    <def m="|"><d>|</d></def> 
    <def m="nbsp"><d>&nbsp;</d></def>     <!-- non-breaking space -->
    <def m="shortdash"><d>&shy;</d></def> <!-- The normal dash -->
    <def m="ndash"><d>&ndash;</d></def>   <!-- A longer dash -->
    <def m="mdash"><d>&mdash;</d></def>   <!-- An even longer dash -->

    <def m="sharp"><d>&#x266f;</d></def>  <!-- Music sharp sign -->

    <!-- Simple math operators -->
    <def m="not" n="1"> <e n="mo"><d><lookup>accent-not-{{0}}</lookup></d></e></def>
    <dictentry key="accent-not-=">&#x2260;</dictentry>
    <dictentry key="accent-not-in">&#x2209;</dictentry>
    <dictentry key="accent-not-&sube;">&#x2288;</dictentry>

    <def m="leq">                <e n="mo"><d>&le;</d></e></def>
    <def m="geq">                <e n="mo"><d>&ge;</d></e></def> 
    <def m="lt">                 <e n="mo"><d>&lt;</d></e></def>
    <def m="gt">                 <e n="mo"><d>&gt;</d></e></def> 
    <def m="ldots">              <e n="mo"><d>&#x2026;</d></e></def> <!-- vertical ellipsis -->
    <def m="cdots">              <e n="mo"><d>&#x22EF;</d></e></def> <!-- vertical ellipsis -->
    <def m="vdots">              <e n="mo"><d>&#x205D;</d></e></def> <!-- vertical ellipsis -->
    <def m="ddots">              <e n="mo"><d>&#x22F1;</d></e></def> <!-- diagonal ellipsis -->
    <def m="cdot">               <e n="mo"><d>&sdot;</d></e></def>
    <def m="times">              <e n="mo"><d>&times;</d></e></def>
    <def m="forall">             <e n="mo"><d>&forall;</d></e></def>
    <def m="in">                 <e n="mo"><d>&isin;</d></e></def>
    <def m="subset">             <e n="mo"><d>&sub;</d></e></def>
    <def m="approx">             <e n="mo"><d>&#x2248;</d></e></def>
    <def m="Rightarrow">         <e n="mo"><d>&#x21d2;</d></e></def>
    <def m="Leftrightarrow">     <e n="mo"><d>&#x21d4;</d></e></def>
    <def m="rightarrow">         <e n="mo"><d>&#x2192;</d></e></def>                     
    <def m="infty">              <e n="mo"><d>&infin;</d></e></def>
    <def m="cup">                <e n="mo"><d>&cup;</d></e></def>
    <def m="cap">                <e n="mo"><d>&cap;</d></e></def>
    <def m="emptyset">           <e n="mo"><d>&empty;</d></e></def>
   
    <def m="subseteq">           <e n="mi"><d>&sube;</d></e></def>
    <def m="notsubseteq">        <e n="mi"><d>&#x2288;</d></e></def> <!-- same as \not{\subseteq}-->
    <def m="setminus">           <e n="mi"><d>&#x2216;</d></e></def>
    
    <def m="nabla">              <e n="mi"><d>&nabla;</d></e></def>
    <!-- Greek letter formath -->
    <def m="alpha">              <e n="mi"><d>&alpha;</d></e></def>
    <def m="beta">               <e n="mi"><d>&beta;</d></e></def>
    <def m="gamma">              <e n="mi"><d>&gamma;</d></e></def>
    <def m="delta">              <e n="mi"><d>&delta;</d></e></def>
    <def m="epsilon">            <e n="mi"><d>&epsilon;</d></e></def>
    <def m="varepsilon">         <e n="mi"><d>&epsilon;</d></e></def>
    <def m="zeta">               <e n="mi"><d>&zeta;</d></e></def>
    <def m="eta">                <e n="mi"><d>&eta;</d></e></def>
    <def m="theta">              <e n="mi"><d>&theta;</d></e></def>
    <def m="iota">               <e n="mi"><d>&iota;</d></e></def>
    <def m="kappa">              <e n="mi"><d>&kappa;</d></e></def>
    <def m="lambda">             <e n="mi"><d>&lambda;</d></e></def>
    <def m="mu">                 <e n="mi"><d>&mu;</d></e></def>
    <def m="nu">                 <e n="mi"><d>&nu;</d></e></def>
    <def m="xi">                 <e n="mi"><d>&xi;</d></e></def>
    <def m="omicron">            <e n="mi"><d>&omicron;</d></e></def>
    <def m="pi">                 <e n="mi"><d>&pi;</d></e></def>
    <def m="rho">                <e n="mi"><d>&rho;</d></e></def>
    <def m="sigma">              <e n="mi"><d>&sigma;</d></e></def>
    <def m="tau">                <e n="mi"><d>&tau;</d></e></def>
    <def m="upsilon">            <e n="mi"><d>&upsilon;</d></e></def>
    <def m="phi">                <e n="mi"><d>&phi;</d></e></def>
    <def m="chi">                <e n="mi"><d>&chi;</d></e></def>
    <def m="psi">                <e n="mi"><d>&psi;</d></e></def>
    <def m="omega">              <e n="mi"><d>&omega;</d></e></def>
    
    <def m="Alpha">              <e n="mi"><d>&Alpha;</d></e></def>
    <def m="Beta">               <e n="mi"><d>&Beta;</d></e></def>
    <def m="Gamma">              <e n="mi"><d>&Gamma;</d></e></def>
    <def m="Delta">              <e n="mi"><d>&Delta;</d></e></def>
    <def m="Epsilon">            <e n="mi"><d>&Epsilon;</d></e></def>
    <def m="Zeta">               <e n="mi"><d>&Zeta;</d></e></def>
    <def m="Eta">                <e n="mi"><d>&Eta;</d></e></def>
    <def m="Theta">              <e n="mi"><d>&Theta;</d></e></def>
    <def m="Iota">               <e n="mi"><d>&Iota;</d></e></def>
    <def m="Kappa">              <e n="mi"><d>&Kappa;</d></e></def>
    <def m="Lambda">             <e n="mi"><d>&Lambda;</d></e></def>
    <def m="Mu">                 <e n="mi"><d>&Mu;</d></e></def>
    <def m="Nu">                 <e n="mi"><d>&Nu;</d></e></def>
    <def m="Xi">                 <e n="mi"><d>&Xi;</d></e></def>
    <def m="Omicron">            <e n="mi"><d>&Omicron;</d></e></def>
    <def m="Pi">                 <e n="mi"><d>&Pi;</d></e></def>
    <def m="Rho">                <e n="mi"><d>&Rho;</d></e></def>
    <def m="Sigma">              <e n="mi"><d>&Sigma;</d></e></def>
    <def m="Tau">                <e n="mi"><d>&Tau;</d></e></def>
    <def m="Upsilon">            <e n="mi"><d>&Upsilon;</d></e></def>
    <def m="Phi">                <e n="mi"><d>&Phi;</d></e></def>
    <def m="Chi">                <e n="mi"><d>&Chi;</d></e></def>
    <def m="Psi">                <e n="mi"><d>&Psi;</d></e></def>
    <def m="Omega">              <e n="mi"><d>&Omega;</d></e></def>
</defines>
